# Generated by Django 6.0.3 on 2026-03-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesnapshot',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
