# Generated by Django 6.0.3 on 2026-03-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_pricesnapshot_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
